### ISSUE TITLE
[Suggestion][Ryandw11]Suggestion #1

### ISSUE THREAD

**Issue by ryandw11** [KingLinux01/ServerInfo-Spigot-Public#1]
Recode everything.

Edit:
Just do my suggest. I'm not going to copy and past it here.

**Comment by KingLinux01** [comment]
I will I lost the source code It has to be redone. With some new features.

**Comment by KingLinux01** [comment]
All your suggestions Wil be added.

**Comment by ryandw11** [comment]
Yay! Also if you want to do a motd. I found a method. bukkit.getServer().getMotd();

**Comment by KingLinux01** [comment]
Thread Closed.
